name: Work

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to"
        default: "staging"
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
